#!/bin/bash

echo "Hello world"

# disable serial access
sudo wget https://raw.githubusercontent.com/virtusai/rpi-serial-console/master/rpi-serial-console -O /usr/bin/rpi-serial-console
sudo chmod +x /usr/bin/rpi-serial-console
sudo /usr/bin/rpi-serial-console disable

echo "Done serial processing..."

# create folders
sudo mkdir -p /home/pirate/docker-manager/store && mkdir /data

echo "Done folder structure..."

# docker login, pull & run
sudo docker login -u $1 -p $2 ci.virtusai.me:5001
sleep 20
sudo docker pull ci.virtusai.me:5001/gateway_dockermanager:latest
sleep 20
sudo docker run -d --net=host --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /home/pirate/docker-manager/store:/usr/src/app/store -v /data:/data --name=docker-manager --rm ci.virtusai.me:5001/gateway_dockermanager:latest

echo "Done docker startup..."