#!/bin/bash

# starting state
STATE='disableSerial'

function disableSerial {
    sudo wget https://raw.githubusercontent.com/virtusai/rpi-serial-console/master/rpi-serial-console -O /usr/bin/rpi-serial-console
    sudo chmod +x /usr/bin/rpi-serial-console
    sudo /usr/bin/rpi-serial-console disable
    STATE='createFolders'
    echo "Done serial processing..."
}

function createFolders {
    sudo mkdir -p /home/pirate/docker-manager/store && mkdir /data
    STATE='docker'
    echo "Done folder structure..."
}

function docker {
    sudo docker login -u $1 -p $2 ci.virtusai.me:5001
    sleep 20
    sudo docker pull ci.virtusai.me:5001/gateway_dockermanager:latest
    sleep 20
    sudo docker run -d --net=host --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /home/pirate/docker-manager/store:/usr/src/app/store -v /data:/data --name=docker-manager --rm ci.virtusai.me:5001/gateway_dockermanager:latest

    echo "Done docker startup..."
    # Exit state
    exit 0
}

function preExit {
    echo "Exiting script.."
}

function main {
    while true
    do
        $STATE
    done
}


# Well Behaved Exit
trap preExit EXIT
# call mainLoop
main