#!/bin/bash

# vars
DOCKER_USER=$1
DOCKER_PASS=$2

# starting state
STATE='checkEth0'

function checkEth0 {
    eth_on=$(cat /sys/class/net/eth0/operstate | grep -c up)
    ppp_on=$(route -n | grep -c ^0.0.0.0.*ppp0)
    if [ $eth_on -eq 1 ] && [ $ppp_on -eq 1 ]; then
        route del default ppp0
        echo "deleted ppp0 route"
        STATE='changeDNS'
    else
        echo "eth0 = $eth_on  ppp_on = $ppp_on"
        # TODO check GSM !!
        STATE='changeDNS'
    fi
}

function changeDNS {
    echo -e "nameserver 8.8.8.8\nameserver 8.8.4.4" > /etc/resolv.conf
    STATE='disableSerial'
}

function disableSerial {
    [[ -f /usr/bin/rpi-serial-console ]] && echo "Already has rpi-serial-console" || wget --no-cache --quiet https://raw.githubusercontent.com/virtusai/rpi-serial-console/master/rpi-serial-console -O /usr/bin/rpi-serial-console
    chmod +x /usr/bin/rpi-serial-console
    /usr/bin/rpi-serial-console disable
    STATE='createFolders'
    echo "Done serial processing..."
}

function createFolders {
    mkdir -p /home/pirate/docker-manager/store && mkdir /data
    STATE='dockerStart'
    echo "Done folder structure..."
}

function dockerStart {
    docker login -u $DOCKER_USER -p $DOCKER_PASS ci.virtusai.me:5001
    sleep 20
    docker pull ci.virtusai.me:5001/gateway_dockermanager:latest
    sleep 20
    docker run -d --net=host --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /home/pirate/docker-manager/store:/usr/src/app/store -v /data:/data --name=docker-manager --rm ci.virtusai.me:5001/gateway_dockermanager:latest

    echo "Done docker startup..."
    # Exit state
    exit 0
}

function preExit {
    echo "Exiting script.."
}

function main {
    while true
    do
        $STATE
    done
}

# Well Behaved Exit
trap preExit EXIT
# call mainLoop
main